import type { Metadata } from "next";
import "./globals.css";
import { ModalProvider } from "@/components/modals/ModalContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`antialiased`}
      >
        {/* ✅ Bọc toàn bộ ứng dụng trong ModalProvider */}
        <ModalProvider>
          {children}
        </ModalProvider>
      </body>
    </html>
  );
}
